### ISSUE TITLE
PYPI package

### ISSUE THREAD

**Issue by scholer** [WikiToLearn/texla#3]
It would be convenient to have this package on PYPI (https://pypi.python.org/pypi) for easy install with ```pip install texla```.

**Comment by valsdav** [comment]
Thanks for your suggestion! I'll look into it. First of all, I have to standardise the package.

Davide

**Comment by valsdav** [comment]
HI!

I have put on Pypi a first version of the Texla package!
https://pypi.python.org/pypi/texla/0.1.2

Thanks again for the suggestion!
